eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084
spring:
  application:
    name:  USER-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Rps@12345
    url: jdbc:mysql://localhost:3306/global_bank
    username: root
  jpa:
    hibernate:
      ddl-auto: update


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
